# Generated by Django 2.1.4 on 2018-12-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='draft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
