# Generated by Django 2.1.4 on 2018-12-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181218_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='assigned_user',
            new_name='assigned_users',
        ),
    ]
