# Generated by Django 2.1.4 on 2018-12-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20181225_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='priority',
        ),
        migrations.AddField(
            model_name='logentry',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
