# Generated by Django 2.1.4 on 2019-01-11 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logentry',
            name='notify_users',
            field=models.ManyToManyField(related_name='notify_log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
