# Generated by Django 2.1.4 on 2019-01-11 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190111_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='notify_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='notify_log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
